In [1]:
#Question 1
def stringPer(s):
    ans = []
    low = 0
    high = len(s)
    for c in s:
        if c == 'I':
            ans.append(low)
            low+=1
        else:
            ans.append(high)
            high-=1
    return ans + [high]
s = "IDID"
print(stringPer(s))

[0, 4, 1, 3, 2]


In [2]:
#Question 2
def searchMatrix(mat,target):
    R, C = len(mat), len(mat[0])
    l, r = 0, R*C-1
    while l <= r:
        mid = l + (r-l)//2
        row, col = mid // C, mid % C
        if mat[row][col] < target:
            l = mid + 1
        elif mat[row][col] > target:
            r = mid - 1
        else:
            return True
    return False
matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]]
target = 3
print(searchMatrix(matrix,target))

True


In [3]:
#Question 3
def validMountainArray(arr):
    if len(arr) < 3:
        return False;
    l = 0;
    r = len(arr) - 1
    while l + 1 < len(arr) - 1 and arr[l] < arr[l + 1]: 
        l += 1
    while r - 1 > 0 and arr[r] < arr[r - 1]: 
        r -= 1
    return l == r
arr = [2,1]
print(validMountainArray(arr))

False


In [4]:
#Question 4
def findMaxSubArray(nums):
    count = {0: -1}
    ml = cd = 0
    for i, num in enumerate(nums):
        if num == 1:
            cd += 1
        else:
            cd=-1
        if cd in count:
            ml = max(ml, i - count[cd])
        else:
            count[cd] = i
    return ml
nums = [0,1]
print(findMaxSubArray(nums))

2


In [5]:
#Question 5
import numpy as np
def minProduct(nums1,nums2):
    nums1.sort()
    nums2.sort(reverse=True)
    newmat = np.matmul(nums1,nums2)
    return newmat.sum()
nums1 = [5,3,4,2]
nums2 = [4,2,2,5]
print(minProduct(nums1,nums2))

40


In [6]:
#Question 6
from collections import Counter
def findOriginalArray(nums):
    ans = [] 
    vacans = [] 
    if len(nums)%2 != 0 :
        return ans
    nums.sort()
    temp = Counter(nums)
    for i in nums:    
        if temp[i] == 0:  
            continue
        else:
            if temp.get(2*i,0) >= 1:
                ans.append(i)
                temp[2*i] -= 1
                temp[i] -= 1
            else:        
                return vacans
    return ans
changed = [1,3,4,2,6,8]
print(findOriginalArray(changed))

[1, 3, 4]


In [7]:
#Question 7
import numpy as np
def spiralMatrix(n):
    result = np.zeros((n,n))
    top, bottom, left, right = 0, n - 1, 0, n - 1
    cnt=1
    while top <= bottom and left <= right:
        for i in range(left, right + 1):
            result[top][i]=cnt
            cnt+=1
        top += 1
        dn=top
        for i in range(top, bottom + 1):
            result[i][bottom]=cnt
            cnt+=1
        right -= 1
        if top <= bottom:
            for i in range(right, left - 1, -1):
                result[bottom][i]=cnt
                cnt+=1
            bottom -= 1
        if left <= right:
            for i in range(bottom, top - 1, -1):
                result[i][left]=cnt
                cnt+=1
            left += 1
    return result
n=int(input("Enter Number n:"))
print(spiralMatrix(n))

Enter Number n:3
[[1. 2. 3.]
 [8. 9. 4.]
 [7. 6. 5.]]


In [8]:
#Question 8
import numpy as np
def matrixMultiplication(mat1,mat2):
    mat1=np.array(mat1)
    mat2=np.array(mat2)
    mat3= np.matmul(mat1,mat2)
    return mat3
mat1 = [[1,0,0],[-1,0,3]]
mat2 = [[7,0,0],[0,0,0],[0,0,1]]
print(matrixMultiplication(mat1,mat2))

[[ 7  0  0]
 [-7  0  3]]
